### ISSUE TITLE
No code to handle frameweight_sample in  ~/arti_mani/envs  /arti_mani.py

### ISSUE THREAD

**Issue by haicaoha** [THU-VCLab/Part-Guided-3D-RL-for-Sim2Real-Articulated-Object-Manipulation#7]
When training and testing RL strategies (arti_mani/algorithms/rl_iam/sac_train_segpts_PNfeat.py  & arti_mani/algorithms/rl_iam/sac_eval_segpts_PNfeat.py), you can choose the **frameweight_sample** method when selecting the sampling method, but there is no code for processing **frameweight_sample** in ~/arti_mani/envs/arti_mani.py.
Below is the code in ~/arti_mani/envs/arti_mani.py that declares the sampling method：（line138-line151 in arti_mani.py）

 ```
self.sample_mode = sample_mode
        self.sample_num = sample_num
        if sample_mode == "full_downsample":
            self.sampler = UniDownsampler(sample_num=sample_num)
        elif sample_mode == "score_sample":
            self.sampler = ScoreSampler(sample_num=sample_num)
        elif sample_mode == "fps_sample":
            self.sampler = FPSSampler(sample_num=sample_num)
        elif sample_mode == "random_sample":
            self.sampler = RandomSampler(sample_num=sample_num)
        elif sample_mode == None:
            self.sampler = None
        else:
            raise NotImplementedError(sample_mode)
```

**Comment by xspkwy** [comment]
Hello, actually you're right. In out implementation, the FUS strategy is just used to mitigate the segmentation noise in the real environment, you can refer to these demos in our videos. 

In simulation, since our PartSeg model was trained from synthetic data just in the same simulator, the segmentation results are mostly convincible. So we can just use random sampling to sample part points, and FUS is not necessary. Also, some segmentation noise during the training is not totally harmful, and it might improve the RL model's robustness instead.

BTW, during the training, I think you could just use the part segmentation groundth results with a little noise, which can improve the training effeciency due to the saved segmentation inferrence time. I did not conduct the experiments but I think it is effective.
